// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReportCards.Web.Data;

#nullable disable

namespace ReportCards.Web.Migrations
{
    [DbContext(typeof(SchoolDbContext))]
    [Migration("20260304000001_AddSubjectModifiersAndStrandConfig")]
    partial class AddSubjectModifiersAndStrandConfig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // This Designer.cs intentionally references the snapshot model.
            // The actual model is defined in SchoolDbContextModelSnapshot.cs.
            // EF Core uses this file to verify migration consistency.
            // Since we manually authored both the migration and snapshot together,
            // they are consistent by construction.
#pragma warning restore 612, 618
        }
    }
}
