// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReportCards.Web.Data;

#nullable disable

namespace ReportCards.Web.Migrations
{
    [DbContext(typeof(SchoolDbContext))]
    [Migration("20260223191207_AddHomeworkAnalysis")]
    partial class AddHomeworkAnalysis
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ReportCards.Web.Data.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("TeacherId");

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("ReportCards.Web.Data.Assessment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("LastUpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("StudentLearningItemId")
                        .HasColumnType("int");

                    b.Property<int>("TermInstanceId")
                        .HasColumnType("int");

                    b.Property<decimal?>("ValueNumber")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("ValueText")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TermInstanceId");

                    b.HasIndex("StudentLearningItemId", "TermInstanceId")
                        .IsUnique();

                    b.ToTable("Assessments");
                });

            modelBuilder.Entity("ReportCards.Web.Data.ClassGroupInstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassGroupTypeId")
                        .HasColumnType("int");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TermInstanceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClassGroupTypeId");

                    b.HasIndex("TermInstanceId");

                    b.ToTable("ClassGroupInstances");
                });

            modelBuilder.Entity("ReportCards.Web.Data.ClassGroupType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ClassGroupTypes");
                });

            modelBuilder.Entity("ReportCards.Web.Data.CurriculumClassTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CurriculumGradeTemplateId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CurriculumGradeTemplateId");

                    b.ToTable("CurriculumClassTemplates");
                });

            modelBuilder.Entity("ReportCards.Web.Data.CurriculumGradeTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CurriculumSchemaId")
                        .HasColumnType("int");

                    b.Property<int>("GradeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CurriculumSchemaId");

                    b.HasIndex("GradeId");

                    b.ToTable("CurriculumGradeTemplates");
                });

            modelBuilder.Entity("ReportCards.Web.Data.CurriculumSchema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RawArtifactData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Version")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CurriculumSchemas");
                });

            modelBuilder.Entity("ReportCards.Web.Data.CurriculumSubjectTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CurriculumClassTemplateId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CurriculumClassTemplateId");

                    b.ToTable("CurriculumSubjectTemplates");
                });

            modelBuilder.Entity("ReportCards.Web.Data.Enrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassGroupInstanceId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("EnrolledOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("GradeId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("TermInstanceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClassGroupInstanceId");

                    b.HasIndex("GradeId");

                    b.HasIndex("StudentId");

                    b.HasIndex("TermInstanceId");

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("ReportCards.Web.Data.Grade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassGroupTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClassGroupTypeId", "Name")
                        .IsUnique();

                    b.ToTable("Grades");
                });

            modelBuilder.Entity("ReportCards.Web.Data.GradingScale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplaySuffix")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("MaxValue")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal?>("MinValue")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Step")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<int>("ValueType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("GradingScales");
                });

            modelBuilder.Entity("ReportCards.Web.Data.GradingScaleOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GradingScaleId")
                        .HasColumnType("int");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GradingScaleId", "Label")
                        .IsUnique();

                    b.ToTable("GradingScaleOptions");
                });

            modelBuilder.Entity("ReportCards.Web.Data.HomeworkAnalysis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AiDetectionSummary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AiLikelihood")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("AnalyzedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("CheckedAiGenerated")
                        .HasColumnType("bit");

                    b.Property<bool>("CheckedGrammar")
                        .HasColumnType("bit");

                    b.Property<bool>("CheckedRubric")
                        .HasColumnType("bit");

                    b.Property<bool>("CheckedSpelling")
                        .HasColumnType("bit");

                    b.Property<string>("ClassGroupName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GradeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GrammarScore")
                        .HasColumnType("int");

                    b.Property<string>("GrammarSummary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OverallSummary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RubricScore")
                        .HasColumnType("int");

                    b.Property<string>("RubricSummary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SpellingScore")
                        .HasColumnType("int");

                    b.Property<string>("SpellingSummary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeacherNote")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HomeworkAnalyses");
                });

            modelBuilder.Entity("ReportCards.Web.Data.ReportTemplateFieldMap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PdfFieldName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportDestinationKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TermInstanceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TermInstanceId");

                    b.ToTable("ReportTemplateFieldMaps");
                });

            modelBuilder.Entity("ReportCards.Web.Data.SchoolYear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SchoolYears");
                });

            modelBuilder.Entity("ReportCards.Web.Data.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("InactivatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("InactivatedReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("ReportCards.Web.Data.StudentLearningItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EnrollmentId")
                        .HasColumnType("int");

                    b.Property<int>("GradingScaleId")
                        .HasColumnType("int");

                    b.Property<int>("ItemType")
                        .HasColumnType("int");

                    b.Property<int?>("YearClassOfferingId")
                        .HasColumnType("int");

                    b.Property<int?>("YearSubjectOfferingId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EnrollmentId");

                    b.HasIndex("GradingScaleId");

                    b.HasIndex("YearClassOfferingId");

                    b.HasIndex("YearSubjectOfferingId");

                    b.ToTable("StudentLearningItems");
                });

            modelBuilder.Entity("ReportCards.Web.Data.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset?>("InactivatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("InactivatedReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("ReportCards.Web.Data.TeacherAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassGroupInstanceId")
                        .HasColumnType("int");

                    b.Property<int?>("ClassGroupTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("GradeId")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClassGroupInstanceId");

                    b.HasIndex("ClassGroupTypeId");

                    b.HasIndex("GradeId");

                    b.HasIndex("TeacherId");

                    b.ToTable("TeacherAssignments");
                });

            modelBuilder.Entity("ReportCards.Web.Data.TermGradeGradingRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassGroupTypeId")
                        .HasColumnType("int");

                    b.Property<int>("GradeId")
                        .HasColumnType("int");

                    b.Property<int>("GradingScaleId")
                        .HasColumnType("int");

                    b.Property<int>("TermInstanceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClassGroupTypeId");

                    b.HasIndex("GradeId");

                    b.HasIndex("GradingScaleId");

                    b.HasIndex("TermInstanceId", "ClassGroupTypeId", "GradeId")
                        .IsUnique();

                    b.ToTable("TermGradeGradingRules");
                });

            modelBuilder.Entity("ReportCards.Web.Data.TermInstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SchoolYearId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("SchoolYearId");

                    b.ToTable("TermInstances");
                });

            modelBuilder.Entity("ReportCards.Web.Data.YearClassOffering", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CurriculumClassTemplateId")
                        .HasColumnType("int");

                    b.Property<int>("GradeId")
                        .HasColumnType("int");

                    b.Property<int?>("GradingScaleId")
                        .HasColumnType("int");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("ReportDestinationKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearCurriculumId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CurriculumClassTemplateId");

                    b.HasIndex("GradeId");

                    b.HasIndex("GradingScaleId");

                    b.HasIndex("YearCurriculumId");

                    b.ToTable("YearClassOfferings");
                });

            modelBuilder.Entity("ReportCards.Web.Data.YearCurriculum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("AppliedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CurriculumSchemaId")
                        .HasColumnType("int");

                    b.Property<int>("SchoolYearId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CurriculumSchemaId");

                    b.HasIndex("SchoolYearId")
                        .IsUnique();

                    b.ToTable("YearCurriculums");
                });

            modelBuilder.Entity("ReportCards.Web.Data.YearSubjectOffering", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CurriculumSubjectTemplateId")
                        .HasColumnType("int");

                    b.Property<int?>("GradingScaleId")
                        .HasColumnType("int");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("ReportDestinationKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearClassOfferingId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CurriculumSubjectTemplateId");

                    b.HasIndex("GradingScaleId");

                    b.HasIndex("YearClassOfferingId");

                    b.ToTable("YearSubjectOfferings");
                });

            modelBuilder.Entity("ReportCards.Web.Data.AppUser", b =>
                {
                    b.HasOne("ReportCards.Web.Data.Teacher", "Teacher")
                        .WithMany("AppUsers")
                        .HasForeignKey("TeacherId");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("ReportCards.Web.Data.Assessment", b =>
                {
                    b.HasOne("ReportCards.Web.Data.StudentLearningItem", "StudentLearningItem")
                        .WithMany("Assessments")
                        .HasForeignKey("StudentLearningItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReportCards.Web.Data.TermInstance", "TermInstance")
                        .WithMany("Assessments")
                        .HasForeignKey("TermInstanceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("StudentLearningItem");

                    b.Navigation("TermInstance");
                });

            modelBuilder.Entity("ReportCards.Web.Data.ClassGroupInstance", b =>
                {
                    b.HasOne("ReportCards.Web.Data.ClassGroupType", "ClassGroupType")
                        .WithMany("ClassGroupInstances")
                        .HasForeignKey("ClassGroupTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReportCards.Web.Data.TermInstance", "TermInstance")
                        .WithMany("ClassGroupInstances")
                        .HasForeignKey("TermInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassGroupType");

                    b.Navigation("TermInstance");
                });

            modelBuilder.Entity("ReportCards.Web.Data.CurriculumClassTemplate", b =>
                {
                    b.HasOne("ReportCards.Web.Data.CurriculumGradeTemplate", "CurriculumGradeTemplate")
                        .WithMany("ClassTemplates")
                        .HasForeignKey("CurriculumGradeTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurriculumGradeTemplate");
                });

            modelBuilder.Entity("ReportCards.Web.Data.CurriculumGradeTemplate", b =>
                {
                    b.HasOne("ReportCards.Web.Data.CurriculumSchema", "CurriculumSchema")
                        .WithMany("GradeTemplates")
                        .HasForeignKey("CurriculumSchemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReportCards.Web.Data.Grade", "Grade")
                        .WithMany("CurriculumGradeTemplates")
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CurriculumSchema");

                    b.Navigation("Grade");
                });

            modelBuilder.Entity("ReportCards.Web.Data.CurriculumSubjectTemplate", b =>
                {
                    b.HasOne("ReportCards.Web.Data.CurriculumClassTemplate", "CurriculumClassTemplate")
                        .WithMany("SubjectTemplates")
                        .HasForeignKey("CurriculumClassTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurriculumClassTemplate");
                });

            modelBuilder.Entity("ReportCards.Web.Data.Enrollment", b =>
                {
                    b.HasOne("ReportCards.Web.Data.ClassGroupInstance", "ClassGroupInstance")
                        .WithMany("Enrollments")
                        .HasForeignKey("ClassGroupInstanceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ReportCards.Web.Data.Grade", "Grade")
                        .WithMany("Enrollments")
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ReportCards.Web.Data.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ReportCards.Web.Data.TermInstance", "TermInstance")
                        .WithMany("Enrollments")
                        .HasForeignKey("TermInstanceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ClassGroupInstance");

                    b.Navigation("Grade");

                    b.Navigation("Student");

                    b.Navigation("TermInstance");
                });

            modelBuilder.Entity("ReportCards.Web.Data.Grade", b =>
                {
                    b.HasOne("ReportCards.Web.Data.ClassGroupType", "ClassGroupType")
                        .WithMany("Grades")
                        .HasForeignKey("ClassGroupTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassGroupType");
                });

            modelBuilder.Entity("ReportCards.Web.Data.GradingScaleOption", b =>
                {
                    b.HasOne("ReportCards.Web.Data.GradingScale", "GradingScale")
                        .WithMany("Options")
                        .HasForeignKey("GradingScaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GradingScale");
                });

            modelBuilder.Entity("ReportCards.Web.Data.ReportTemplateFieldMap", b =>
                {
                    b.HasOne("ReportCards.Web.Data.TermInstance", "TermInstance")
                        .WithMany("ReportTemplateFieldMaps")
                        .HasForeignKey("TermInstanceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("TermInstance");
                });

            modelBuilder.Entity("ReportCards.Web.Data.StudentLearningItem", b =>
                {
                    b.HasOne("ReportCards.Web.Data.Enrollment", "Enrollment")
                        .WithMany("LearningItems")
                        .HasForeignKey("EnrollmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReportCards.Web.Data.GradingScale", "GradingScale")
                        .WithMany("StudentLearningItems")
                        .HasForeignKey("GradingScaleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ReportCards.Web.Data.YearClassOffering", "YearClassOffering")
                        .WithMany("StudentLearningItems")
                        .HasForeignKey("YearClassOfferingId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ReportCards.Web.Data.YearSubjectOffering", "YearSubjectOffering")
                        .WithMany("StudentLearningItems")
                        .HasForeignKey("YearSubjectOfferingId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Enrollment");

                    b.Navigation("GradingScale");

                    b.Navigation("YearClassOffering");

                    b.Navigation("YearSubjectOffering");
                });

            modelBuilder.Entity("ReportCards.Web.Data.TeacherAssignment", b =>
                {
                    b.HasOne("ReportCards.Web.Data.ClassGroupInstance", "ClassGroupInstance")
                        .WithMany("TeacherAssignments")
                        .HasForeignKey("ClassGroupInstanceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ReportCards.Web.Data.ClassGroupType", null)
                        .WithMany("TeacherAssignments")
                        .HasForeignKey("ClassGroupTypeId");

                    b.HasOne("ReportCards.Web.Data.Grade", "Grade")
                        .WithMany("TeacherAssignments")
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ReportCards.Web.Data.Teacher", "Teacher")
                        .WithMany("Assignments")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ClassGroupInstance");

                    b.Navigation("Grade");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("ReportCards.Web.Data.TermGradeGradingRule", b =>
                {
                    b.HasOne("ReportCards.Web.Data.ClassGroupType", "ClassGroupType")
                        .WithMany("GradingRules")
                        .HasForeignKey("ClassGroupTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ReportCards.Web.Data.Grade", "Grade")
                        .WithMany("GradingRules")
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ReportCards.Web.Data.GradingScale", "GradingScale")
                        .WithMany("GradingRules")
                        .HasForeignKey("GradingScaleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ReportCards.Web.Data.TermInstance", "TermInstance")
                        .WithMany("GradingRules")
                        .HasForeignKey("TermInstanceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ClassGroupType");

                    b.Navigation("Grade");

                    b.Navigation("GradingScale");

                    b.Navigation("TermInstance");
                });

            modelBuilder.Entity("ReportCards.Web.Data.TermInstance", b =>
                {
                    b.HasOne("ReportCards.Web.Data.SchoolYear", "SchoolYear")
                        .WithMany("TermInstances")
                        .HasForeignKey("SchoolYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SchoolYear");
                });

            modelBuilder.Entity("ReportCards.Web.Data.YearClassOffering", b =>
                {
                    b.HasOne("ReportCards.Web.Data.CurriculumClassTemplate", "CurriculumClassTemplate")
                        .WithMany("YearClassOfferings")
                        .HasForeignKey("CurriculumClassTemplateId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ReportCards.Web.Data.Grade", "Grade")
                        .WithMany("YearClassOfferings")
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ReportCards.Web.Data.GradingScale", "GradingScale")
                        .WithMany()
                        .HasForeignKey("GradingScaleId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ReportCards.Web.Data.YearCurriculum", "YearCurriculum")
                        .WithMany("ClassOfferings")
                        .HasForeignKey("YearCurriculumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurriculumClassTemplate");

                    b.Navigation("Grade");

                    b.Navigation("GradingScale");

                    b.Navigation("YearCurriculum");
                });

            modelBuilder.Entity("ReportCards.Web.Data.YearCurriculum", b =>
                {
                    b.HasOne("ReportCards.Web.Data.CurriculumSchema", "CurriculumSchema")
                        .WithMany("YearCurriculums")
                        .HasForeignKey("CurriculumSchemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReportCards.Web.Data.SchoolYear", "SchoolYear")
                        .WithMany("YearCurriculums")
                        .HasForeignKey("SchoolYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurriculumSchema");

                    b.Navigation("SchoolYear");
                });

            modelBuilder.Entity("ReportCards.Web.Data.YearSubjectOffering", b =>
                {
                    b.HasOne("ReportCards.Web.Data.CurriculumSubjectTemplate", "CurriculumSubjectTemplate")
                        .WithMany("YearSubjectOfferings")
                        .HasForeignKey("CurriculumSubjectTemplateId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ReportCards.Web.Data.GradingScale", "GradingScale")
                        .WithMany()
                        .HasForeignKey("GradingScaleId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ReportCards.Web.Data.YearClassOffering", "YearClassOffering")
                        .WithMany("SubjectOfferings")
                        .HasForeignKey("YearClassOfferingId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CurriculumSubjectTemplate");

                    b.Navigation("GradingScale");

                    b.Navigation("YearClassOffering");
                });

            modelBuilder.Entity("ReportCards.Web.Data.ClassGroupInstance", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("TeacherAssignments");
                });

            modelBuilder.Entity("ReportCards.Web.Data.ClassGroupType", b =>
                {
                    b.Navigation("ClassGroupInstances");

                    b.Navigation("Grades");

                    b.Navigation("GradingRules");

                    b.Navigation("TeacherAssignments");
                });

            modelBuilder.Entity("ReportCards.Web.Data.CurriculumClassTemplate", b =>
                {
                    b.Navigation("SubjectTemplates");

                    b.Navigation("YearClassOfferings");
                });

            modelBuilder.Entity("ReportCards.Web.Data.CurriculumGradeTemplate", b =>
                {
                    b.Navigation("ClassTemplates");
                });

            modelBuilder.Entity("ReportCards.Web.Data.CurriculumSchema", b =>
                {
                    b.Navigation("GradeTemplates");

                    b.Navigation("YearCurriculums");
                });

            modelBuilder.Entity("ReportCards.Web.Data.CurriculumSubjectTemplate", b =>
                {
                    b.Navigation("YearSubjectOfferings");
                });

            modelBuilder.Entity("ReportCards.Web.Data.Enrollment", b =>
                {
                    b.Navigation("LearningItems");
                });

            modelBuilder.Entity("ReportCards.Web.Data.Grade", b =>
                {
                    b.Navigation("CurriculumGradeTemplates");

                    b.Navigation("Enrollments");

                    b.Navigation("GradingRules");

                    b.Navigation("TeacherAssignments");

                    b.Navigation("YearClassOfferings");
                });

            modelBuilder.Entity("ReportCards.Web.Data.GradingScale", b =>
                {
                    b.Navigation("GradingRules");

                    b.Navigation("Options");

                    b.Navigation("StudentLearningItems");
                });

            modelBuilder.Entity("ReportCards.Web.Data.SchoolYear", b =>
                {
                    b.Navigation("TermInstances");

                    b.Navigation("YearCurriculums");
                });

            modelBuilder.Entity("ReportCards.Web.Data.Student", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("ReportCards.Web.Data.StudentLearningItem", b =>
                {
                    b.Navigation("Assessments");
                });

            modelBuilder.Entity("ReportCards.Web.Data.Teacher", b =>
                {
                    b.Navigation("AppUsers");

                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("ReportCards.Web.Data.TermInstance", b =>
                {
                    b.Navigation("Assessments");

                    b.Navigation("ClassGroupInstances");

                    b.Navigation("Enrollments");

                    b.Navigation("GradingRules");

                    b.Navigation("ReportTemplateFieldMaps");
                });

            modelBuilder.Entity("ReportCards.Web.Data.YearClassOffering", b =>
                {
                    b.Navigation("StudentLearningItems");

                    b.Navigation("SubjectOfferings");
                });

            modelBuilder.Entity("ReportCards.Web.Data.YearCurriculum", b =>
                {
                    b.Navigation("ClassOfferings");
                });

            modelBuilder.Entity("ReportCards.Web.Data.YearSubjectOffering", b =>
                {
                    b.Navigation("StudentLearningItems");
                });
#pragma warning restore 612, 618
        }
    }
}
